### ISSUE TITLE
TypeError: reduce() of empty sequence with no initial value

### ISSUE THREAD

**Issue by apanand14** [HughClub/YoloV5-Android#1]
Hello,

thank you for providing onnx2ncnn. I'm trying to run your code and facing this issue which is mentioned below. Can you please look into it and help me if possible. Thank you in advance.

**Traceback (most recent call last):
  File "C:/Developer/Git/Inspection/AI/yolo/yolov5/onnx2ncnn.py", line 43, in <module>
    Run.Run64(file)
  File "C:/Developer/Git/Inspection/AI/yolo/yolov5/onnx2ncnn.py", line 32, in Run64
    Run._run_(file, 64)
  File "C:/Developer/Git/Inspection/AI/yolo/yolov5/onnx2ncnn.py", line 26, in _run_
    p=getRuns()
  File "C:/Developer/Git/Inspection/AI/yolo/yolov5/onnx2ncnn.py", line 6, in getRuns
    rel=reduce(lambda x,y:x if x>y else y,map(lambda x:int(x.split("xp")[1]),os.listdir("./runs")))+1
TypeError: reduce() of empty sequence with no initial value**

**Comment by HUGHNew** [comment]
It was something wrong with my script. I wrote it for myself only so I assumed the model is placed in `weights/` and the files generated will be saved to runs/exp1 (runs/exp2 ...).
What's worse, I assumed the folder **runs/exp0** exist so that I didn't check whether it existed really.
I update the script and it may work now.
Or you can simply type `./onnx2ncnn-64.exe __file.onnx __file.param __file.bin` to generate what you want. (remeber to replace `__file` to your real model file name)

**Comment by apanand14** [comment]
Thank you so much @HUGHNew for helping me out.  I just replaced the def getRuns() function in older code and it ran successfully. Thank you once again for providing utils for converting models easily!!

**Comment by HUGHNew** [comment]
My Pleasure.
